/**
 * Mapeo de campos del sistema a rutas en el objeto Pozo
 * Sincronizado con el modelo de datos real y el Designer
 */

export const FIELD_PATHS: Record<string, string> = {
    // POZO - Identificación
    'pozo_id': 'identificacion.idPozo.value',
    'pozo_fecha': 'identificacion.fecha.value',
    'pozo_coordX': 'identificacion.coordenadaX.value',
    'pozo_coordY': 'identificacion.coordenadaY.value',
    'pozo_latitud': 'identificacion.latitud.value',
    'pozo_longitud': 'identificacion.longitud.value',
    'pozo_enlace': 'identificacion.enlace.value',
    'pozo_levanto': 'identificacion.levanto.value',
    'pozo_estado': 'identificacion.estado.value',

    // POZO - Ubicación
    'pozo_direccion': 'ubicacion.direccion.value',
    'pozo_barrio': 'ubicacion.barrio.value',
    'pozo_localidad': 'ubicacion.localidad.value',
    'pozo_upz': 'ubicacion.upz.value',
    'pozo_profundidad': 'ubicacion.profundidad.value',

    // POZO - Componentes
    'pozo_sistema': 'componentes.sistema.value',
    'pozo_tipoCamara': 'componentes.tipoCamara.value',
    'pozo_estructuraPavimento': 'componentes.estructuraPavimento.value',
    'pozo_materialRasante': 'componentes.materialRasante.value',
    'pozo_estadoRasante': 'componentes.estadoRasante.value',
    'pozo_existeTapa': 'componentes.existeTapa.value',
    'pozo_materialTapa': 'componentes.materialTapa.value',
    'pozo_diametroTapa': 'componentes.diametroTapa.value',
    'pozo_estadoTapa': 'componentes.estadoTapa.value',
    'pozo_existeCono': 'componentes.existeCono.value',
    'pozo_materialCono': 'componentes.materialCono.value',
    'pozo_tipoCono': 'componentes.tipoCono.value',
    'pozo_estadoCono': 'componentes.estadoCono.value',
    'pozo_existeCilindro': 'componentes.existeCilindro.value',
    'pozo_materialCilindro': 'componentes.materialCilindro.value',
    'pozo_diametroCilindro': 'componentes.diametroCilindro.value',
    'pozo_estadoCilindro': 'componentes.estadoCilindro.value',
    'pozo_existeCanuela': 'componentes.existeCanuela.value',
    'pozo_materialCanuela': 'componentes.materialCanuela.value',
    'pozo_estadoCanuela': 'componentes.estadoCanuela.value',
    'pozo_existePeldanos': 'componentes.existePeldanos.value',
    'pozo_numPeldanos': 'componentes.numeroPeldanos.value',
    'pozo_materialPeldanos': 'componentes.materialPeldanos.value',
    'pozo_estadoPeldanos': 'componentes.estadoPeldanos.value',

    // POZO - Observaciones
    'pozo_observaciones': 'observaciones.observaciones.value',

    // TUBERIAS (Hasta 8 slots para diseño flexible)
    'tub_1_diametro': 'tuberias.tuberias[0].diametro.value',
    'tub_1_material': 'tuberias.tuberias[0].material.value',
    'tub_1_estado': 'tuberias.tuberias[0].estado.value',
    'tub_1_orden': 'tuberias.tuberias[0].orden.value',
    'tub_1_batea': 'tuberias.tuberias[0].batea.value',
    'tub_2_diametro': 'tuberias.tuberias[1].diametro.value',
    'tub_2_material': 'tuberias.tuberias[1].material.value',
    'tub_2_estado': 'tuberias.tuberias[1].estado.value',
    'tub_2_orden': 'tuberias.tuberias[1].orden.value',
    'tub_2_batea': 'tuberias.tuberias[1].batea.value',
    'tub_3_diametro': 'tuberias.tuberias[2].diametro.value',
    'tub_3_material': 'tuberias.tuberias[2].material.value',
    'tub_3_estado': 'tuberias.tuberias[2].estado.value',
    'tub_3_orden': 'tuberias.tuberias[2].orden.value',
    'tub_3_batea': 'tuberias.tuberias[2].batea.value',
    'tub_4_diametro': 'tuberias.tuberias[3].diametro.value',
    'tub_4_material': 'tuberias.tuberias[3].material.value',
    'tub_4_estado': 'tuberias.tuberias[3].estado.value',
    'tub_4_orden': 'tuberias.tuberias[3].orden.value',
    'tub_4_batea': 'tuberias.tuberias[3].batea.value',
    'tub_5_diametro': 'tuberias.tuberias[4].diametro.value',
    'tub_5_material': 'tuberias.tuberias[4].material.value',
    'tub_5_estado': 'tuberias.tuberias[4].estado.value',
    'tub_6_diametro': 'tuberias.tuberias[5].diametro.value',
    'tub_6_material': 'tuberias.tuberias[5].material.value',
    'tub_6_estado': 'tuberias.tuberias[5].estado.value',
    'tub_7_diametro': 'tuberias.tuberias[6].diametro.value',
    'tub_7_material': 'tuberias.tuberias[6].material.value',
    'tub_7_estado': 'tuberias.tuberias[6].estado.value',
    'tub_8_diametro': 'tuberias.tuberias[7].diametro.value',
    'tub_8_material': 'tuberias.tuberias[7].material.value',
    'tub_8_estado': 'tuberias.tuberias[7].estado.value',

    // SUMIDEROS (Hasta 4 slots)
    'sum_1_tipo': 'sumideros.sumideros[0].tipoSumidero.value',
    'sum_1_material': 'sumideros.sumideros[0].materialTuberia.value',
    'sum_1_esquema': 'sumideros.sumideros[0].numeroEsquema.value',
    'sum_1_diametro': 'sumideros.sumideros[0].diametro.value',
    'sum_1_hSalida': 'sumideros.sumideros[0].alturaSalida.value',
    'sum_1_hLlegada': 'sumideros.sumideros[0].alturaLlegada.value',
    'sum_2_tipo': 'sumideros.sumideros[1].tipoSumidero.value',
    'sum_2_material': 'sumideros.sumideros[1].materialTuberia.value',
    'sum_2_esquema': 'sumideros.sumideros[1].numeroEsquema.value',
    'sum_2_diametro': 'sumideros.sumideros[1].diametro.value',
    'sum_2_hSalida': 'sumideros.sumideros[1].alturaSalida.value',
    'sum_2_hLlegada': 'sumideros.sumideros[1].alturaLlegada.value',
    'sum_3_tipo': 'sumideros.sumideros[2].tipoSumidero.value',
    'sum_3_material': 'sumideros.sumideros[2].materialTuberia.value',
    'sum_3_esquema': 'sumideros.sumideros[2].numeroEsquema.value',
    'sum_3_diametro': 'sumideros.sumideros[2].diametro.value',
    'sum_3_hSalida': 'sumideros.sumideros[2].alturaSalida.value',
    'sum_3_hLlegada': 'sumideros.sumideros[2].alturaLlegada.value',
    'sum_4_tipo': 'sumideros.sumideros[3].tipoSumidero.value',
    'sum_4_material': 'sumideros.sumideros[3].materialTuberia.value',
    'sum_4_esquema': 'sumideros.sumideros[3].numeroEsquema.value',
    'sum_4_diametro': 'sumideros.sumideros[3].diametro.value',
    'sum_4_hSalida': 'sumideros.sumideros[3].alturaSalida.value',
    'sum_4_hLlegada': 'sumideros.sumideros[3].alturaLlegada.value',

    // FOTOS ESPECÍFICAS (Mapeo por subcategoría)
    'foto_panoramica': 'fotos.fotos[P]',
    'foto_tapa': 'fotos.fotos[T]',
    'foto_interior': 'fotos.fotos[I]',
    'foto_acceso': 'fotos.fotos[A]',
    'foto_fondo': 'fotos.fotos[F]',
    'foto_medicion': 'fotos.fotos[M]',
    'foto_esquema': 'fotos.fotos[L]',

    // ENTRADAS (1-7)
    'foto_entrada_1': 'fotos.fotos[E1]',
    'foto_entrada_2': 'fotos.fotos[E2]',
    'foto_entrada_3': 'fotos.fotos[E3]',
    'foto_entrada_4': 'fotos.fotos[E4]',
    'foto_entrada_5': 'fotos.fotos[E5]',
    'foto_entrada_6': 'fotos.fotos[E6]',
    'foto_entrada_7': 'fotos.fotos[E7]',

    // SALIDAS (1-7)
    'foto_salida_1': 'fotos.fotos[S1]',
    'foto_salida_2': 'fotos.fotos[S2]',
    'foto_salida_3': 'fotos.fotos[S3]',
    'foto_salida_4': 'fotos.fotos[S4]',
    'foto_salida_5': 'fotos.fotos[S5]',
    'foto_salida_6': 'fotos.fotos[S6]',
    'foto_salida_7': 'fotos.fotos[S7]',

    // SUMIDEROS (1-7)
    'foto_sumidero_1': 'fotos.fotos[SUM1]',
    'foto_sumidero_2': 'fotos.fotos[SUM2]',
    'foto_sumidero_3': 'fotos.fotos[SUM3]',
    'foto_sumidero_4': 'fotos.fotos[SUM4]',
    'foto_sumidero_5': 'fotos.fotos[SUM5]',
    'foto_sumidero_6': 'fotos.fotos[SUM6]',
    'foto_sumidero_7': 'fotos.fotos[SUM7]',

    // DESCARGAS (1-7)
    'foto_descarga_1': 'fotos.fotos[D1]',
    'foto_descarga_2': 'fotos.fotos[D2]',
    'foto_descarga_3': 'fotos.fotos[D3]',
    'foto_descarga_4': 'fotos.fotos[D4]',
    'foto_descarga_5': 'fotos.fotos[D5]',
    'foto_descarga_6': 'fotos.fotos[D6]',
    'foto_descarga_7': 'fotos.fotos[D7]',

    // FOTOS GENÉRICAS (Fallback para fotos no clasificadas)
    'foto_1': 'fotos.fotos[0].blobId',
    'foto_2': 'fotos.fotos[1].blobId',
    'foto_3': 'fotos.fotos[2].blobId',
    'foto_4': 'fotos.fotos[3].blobId',
    'foto_5': 'fotos.fotos[4].blobId',
    'foto_6': 'fotos.fotos[5].blobId',
    'foto_7': 'fotos.fotos[6].blobId',
    'foto_8': 'fotos.fotos[7].blobId',
    'foto_9': 'fotos.fotos[8].blobId',
    'foto_10': 'fotos.fotos[9].blobId',
    'foto_11': 'fotos.fotos[10].blobId',
    'foto_12': 'fotos.fotos[11].blobId',

    // Alias heredados del legacy para compatibilidad
    'identificacion.idPozo': 'identificacion.idPozo.value',
    'identificacion.fecha': 'identificacion.fecha.value',
    'identificacion.coordenadaX': 'identificacion.coordenadaX.value',
    'identificacion.coordenadaY': 'identificacion.coordenadaY.value',
};

export const AVAILABLE_DATA_FIELDS = [
    { id: 'pozo_id', label: 'ID del Pozo', category: 'Identificación' },
    { id: 'pozo_fecha', label: 'Fecha', category: 'Identificación' },
    { id: 'pozo_levanto', label: 'Levantó', category: 'Identificación' },
    { id: 'pozo_estado', label: 'Estado', category: 'Identificación' },
    { id: 'pozo_coordX', label: 'Coordenada X', category: 'Ubicación' },
    { id: 'pozo_coordY', label: 'Coordenada Y', category: 'Ubicación' },
    { id: 'pozo_latitud', label: 'Latitud (WGS84)', category: 'Ubicación' },
    { id: 'pozo_longitud', label: 'Longitud (WGS84)', category: 'Ubicación' },
    { id: 'pozo_enlace', label: 'Enlace Google Maps', category: 'Ubicación' },
    { id: 'pozo_direccion', label: 'Dirección', category: 'Ubicación' },
    { id: 'pozo_barrio', label: 'Barrio', category: 'Ubicación' },
    { id: 'pozo_localidad', label: 'Localidad', category: 'Ubicación' },
    { id: 'pozo_upz', label: 'UPZ', category: 'Ubicación' },
    { id: 'pozo_profundidad', label: 'Profundidad', category: 'Ubicación' },
    { id: 'pozo_materialTapa', label: 'Mat. Tapa', category: 'Componentes' },
    { id: 'pozo_estadoTapa', label: 'Estado Tapa', category: 'Componentes' },
    { id: 'pozo_diametroCilindro', label: 'Ø Cilindro', category: 'Componentes' },
    { id: 'pozo_materialCono', label: 'Mat. Cono', category: 'Componentes' },
    { id: 'pozo_materialCanuela', label: 'Mat. Cañuela', category: 'Componentes' },
    { id: 'pozo_numPeldanos', label: 'Nº Peldaños', category: 'Componentes' },
    { id: 'pozo_observaciones', label: 'Observaciones', category: 'Observaciones' },
    { id: 'tub_1_orden', label: 'Tub 1 Orden', category: 'Tuberías' },
    { id: 'tub_1_batea', label: 'Tub 1 Batea', category: 'Tuberías' },
    { id: 'sum_1_esquema', label: 'Sum 1 Esquema', category: 'Sumideros' },
    { id: 'sum_1_diametro', label: 'Sum 1 Ø (pulg)', category: 'Sumideros' },
    { id: 'sum_1_hSalida', label: 'Sum 1 H Salida', category: 'Sumideros' },
    { id: 'sum_1_hLlegada', label: 'Sum 1 H Llegada', category: 'Sumideros' },
    { id: 'foto_panoramica', label: 'Foto Panorámica (P)', category: 'Fotos' },
    { id: 'foto_tapa', label: 'Foto Tapa (T)', category: 'Fotos' },
    { id: 'foto_interior', label: 'Foto Interna (I)', category: 'Fotos' },
    { id: 'foto_acceso', label: 'Foto Acceso (A)', category: 'Fotos' },
    { id: 'foto_fondo', label: 'Foto Fondo (F)', category: 'Fotos' },
    { id: 'foto_medicion', label: 'Foto Medición (M)', category: 'Fotos' },
    { id: 'foto_esquema', label: 'Esquema Localización (L)', category: 'Fotos' },

    // Fotos Entradas
    { id: 'foto_entrada_1', label: 'Foto Entrada 1', category: 'Fotos Tuberías' },
    { id: 'foto_entrada_2', label: 'Foto Entrada 2', category: 'Fotos Tuberías' },
    { id: 'foto_entrada_3', label: 'Foto Entrada 3', category: 'Fotos Tuberías' },
    { id: 'foto_entrada_4', label: 'Foto Entrada 4', category: 'Fotos Tuberías' },
    { id: 'foto_entrada_5', label: 'Foto Entrada 5', category: 'Fotos Tuberías' },
    { id: 'foto_entrada_6', label: 'Foto Entrada 6', category: 'Fotos Tuberías' },
    { id: 'foto_entrada_7', label: 'Foto Entrada 7', category: 'Fotos Tuberías' },

    // Fotos Salidas
    { id: 'foto_salida_1', label: 'Foto Salida 1', category: 'Fotos Tuberías' },
    { id: 'foto_salida_2', label: 'Foto Salida 2', category: 'Fotos Tuberías' },
    { id: 'foto_salida_3', label: 'Foto Salida 3', category: 'Fotos Tuberías' },
    { id: 'foto_salida_4', label: 'Foto Salida 4', category: 'Fotos Tuberías' },
    { id: 'foto_salida_5', label: 'Foto Salida 5', category: 'Fotos Tuberías' },
    { id: 'foto_salida_6', label: 'Foto Salida 6', category: 'Fotos Tuberías' },
    { id: 'foto_salida_7', label: 'Foto Salida 7', category: 'Fotos Tuberías' },

    // Fotos Sumideros
    { id: 'foto_sumidero_1', label: 'Foto Sumidero 1', category: 'Fotos Sumideros' },
    { id: 'foto_sumidero_2', label: 'Foto Sumidero 2', category: 'Fotos Sumideros' },
    { id: 'foto_sumidero_3', label: 'Foto Sumidero 3', category: 'Fotos Sumideros' },
    { id: 'foto_sumidero_4', label: 'Foto Sumidero 4', category: 'Fotos Sumideros' },
    { id: 'foto_sumidero_5', label: 'Foto Sumidero 5', category: 'Fotos Sumideros' },
    { id: 'foto_sumidero_6', label: 'Foto Sumidero 6', category: 'Fotos Sumideros' },
    { id: 'foto_sumidero_7', label: 'Foto Sumidero 7', category: 'Fotos Sumideros' },

    // Fotos Descargas
    { id: 'foto_descarga_1', label: 'Foto Descarga 1', category: 'Fotos Envío' },
    { id: 'foto_descarga_2', label: 'Foto Descarga 2', category: 'Fotos Envío' },
    { id: 'foto_descarga_3', label: 'Foto Descarga 3', category: 'Fotos Envío' },
    { id: 'foto_descarga_4', label: 'Foto Descarga 4', category: 'Fotos Envío' },
    { id: 'foto_descarga_5', label: 'Foto Descarga 5', category: 'Fotos Envío' },
    { id: 'foto_descarga_6', label: 'Foto Descarga 6', category: 'Fotos Envío' },
    { id: 'foto_descarga_7', label: 'Foto Descarga 7', category: 'Fotos Envío' },
];
