/**
 * Mapeo de campos del sistema a rutas en el objeto Pozo
 * Sincronizado con el modelo de datos real y el Designer
 */

export const FIELD_PATHS: Record<string, string> = {
    // POZO - Identificación
    'pozo_id': 'identificacion.idPozo.value',
    'pozo_fecha': 'identificacion.fecha.value',
    'pozo_coordX': 'identificacion.coordenadaX.value',
    'pozo_coordY': 'identificacion.coordenadaY.value',
    'pozo_latitud': 'identificacion.latitud.value',
    'pozo_longitud': 'identificacion.longitud.value',
    'pozo_enlace': 'identificacion.enlace.value',
    'pozo_levanto': 'identificacion.levanto.value',
    'pozo_estado': 'identificacion.estado.value',

    // POZO - Ubicación
    'pozo_direccion': 'ubicacion.direccion.value',
    'pozo_barrio': 'ubicacion.barrio.value',
    'pozo_localidad': 'ubicacion.localidad.value',
    'pozo_upz': 'ubicacion.upz.value',
    'pozo_profundidad': 'ubicacion.profundidad.value',

    // POZO - Componentes
    'pozo_sistema': 'componentes.sistema.value',
    'pozo_tipoCamara': 'componentes.tipoCamara.value',
    'pozo_estructuraPavimento': 'componentes.estructuraPavimento.value',
    'pozo_materialRasante': 'componentes.materialRasante.value',
    'pozo_estadoRasante': 'componentes.estadoRasante.value',
    'pozo_existeTapa': 'componentes.existeTapa.value',
    'pozo_materialTapa': 'componentes.materialTapa.value',
    'pozo_diametroTapa': 'componentes.diametroTapa.value',
    'pozo_estadoTapa': 'componentes.estadoTapa.value',
    'pozo_existeCono': 'componentes.existeCono.value',
    'pozo_materialCono': 'componentes.materialCono.value',
    'pozo_tipoCono': 'componentes.tipoCono.value',
    'pozo_estadoCono': 'componentes.estadoCono.value',
    'pozo_existeCilindro': 'componentes.existeCilindro.value',
    'pozo_materialCilindro': 'componentes.materialCilindro.value',
    'pozo_diametroCilindro': 'componentes.diametroCilindro.value',
    'pozo_estadoCilindro': 'componentes.estadoCilindro.value',
    'pozo_existeCanuela': 'componentes.existeCanuela.value',
    'pozo_materialCanuela': 'componentes.materialCanuela.value',
    'pozo_estadoCanuela': 'componentes.estadoCanuela.value',
    'pozo_existePeldanos': 'componentes.existePeldanos.value',
    'pozo_numPeldanos': 'componentes.numeroPeldanos.value',
    'pozo_materialPeldanos': 'componentes.materialPeldanos.value',
    'pozo_estadoPeldanos': 'componentes.estadoPeldanos.value',

    // POZO - Observaciones
    'pozo_observaciones': 'observaciones.observaciones.value',

    // TUBERIAS (Hasta 8 slots para diseño flexible)
    'tub_1_diametro': 'tuberias.tuberias[0].diametro.value',
    'tub_1_material': 'tuberias.tuberias[0].material.value',
    'tub_1_estado': 'tuberias.tuberias[0].estado.value',
    'tub_1_orden': 'tuberias.tuberias[0].orden.value',
    'tub_1_batea': 'tuberias.tuberias[0].batea.value',
    'tub_2_diametro': 'tuberias.tuberias[1].diametro.value',
    'tub_2_material': 'tuberias.tuberias[1].material.value',
    'tub_2_estado': 'tuberias.tuberias[1].estado.value',
    'tub_2_orden': 'tuberias.tuberias[1].orden.value',
    'tub_2_batea': 'tuberias.tuberias[1].batea.value',
    'tub_3_diametro': 'tuberias.tuberias[2].diametro.value',
    'tub_3_material': 'tuberias.tuberias[2].material.value',
    'tub_3_estado': 'tuberias.tuberias[2].estado.value',
    'tub_3_orden': 'tuberias.tuberias[2].orden.value',
    'tub_3_batea': 'tuberias.tuberias[2].batea.value',
    'tub_4_diametro': 'tuberias.tuberias[3].diametro.value',
    'tub_4_material': 'tuberias.tuberias[3].material.value',
    'tub_4_estado': 'tuberias.tuberias[3].estado.value',
    'tub_4_orden': 'tuberias.tuberias[3].orden.value',
    'tub_4_batea': 'tuberias.tuberias[3].batea.value',
    'tub_5_diametro': 'tuberias.tuberias[4].diametro.value',
    'tub_5_material': 'tuberias.tuberias[4].material.value',
    'tub_5_estado': 'tuberias.tuberias[4].estado.value',
    'tub_5_orden': 'tuberias.tuberias[4].orden.value',
    'tub_5_batea': 'tuberias.tuberias[4].batea.value',
    'tub_6_diametro': 'tuberias.tuberias[5].diametro.value',
    'tub_6_material': 'tuberias.tuberias[5].material.value',
    'tub_6_estado': 'tuberias.tuberias[5].estado.value',
    'tub_6_orden': 'tuberias.tuberias[5].orden.value',
    'tub_6_batea': 'tuberias.tuberias[5].batea.value',
    'tub_7_diametro': 'tuberias.tuberias[6].diametro.value',
    'tub_7_material': 'tuberias.tuberias[6].material.value',
    'tub_7_estado': 'tuberias.tuberias[6].estado.value',
    'tub_7_orden': 'tuberias.tuberias[6].orden.value',
    'tub_7_batea': 'tuberias.tuberias[6].batea.value',
    'tub_8_diametro': 'tuberias.tuberias[7].diametro.value',
    'tub_8_material': 'tuberias.tuberias[7].material.value',
    'tub_8_estado': 'tuberias.tuberias[7].estado.value',
    'tub_8_orden': 'tuberias.tuberias[7].orden.value',
    'tub_8_batea': 'tuberias.tuberias[7].batea.value',
    'tub_1_id': 'tuberias.tuberias[0].idTuberia.value',
    'tub_2_id': 'tuberias.tuberias[1].idTuberia.value',
    'tub_3_id': 'tuberias.tuberias[2].idTuberia.value',
    'tub_4_id': 'tuberias.tuberias[3].idTuberia.value',
    'tub_5_id': 'tuberias.tuberias[4].idTuberia.value',
    'tub_6_id': 'tuberias.tuberias[5].idTuberia.value',
    'tub_7_id': 'tuberias.tuberias[6].idTuberia.value',
    'tub_8_id': 'tuberias.tuberias[7].idTuberia.value',
    'tub_1_z': 'tuberias.tuberias[0].cota.value',
    'tub_1_emboquillado': 'tuberias.tuberias[0].emboquillado.value',
    'tub_2_z': 'tuberias.tuberias[1].cota.value',
    'tub_2_emboquillado': 'tuberias.tuberias[1].emboquillado.value',
    'tub_3_z': 'tuberias.tuberias[2].cota.value',
    'tub_3_emboquillado': 'tuberias.tuberias[2].emboquillado.value',
    'tub_4_z': 'tuberias.tuberias[3].cota.value',
    'tub_4_emboquillado': 'tuberias.tuberias[3].emboquillado.value',
    'tub_5_z': 'tuberias.tuberias[4].cota.value',
    'tub_5_emboquillado': 'tuberias.tuberias[4].emboquillado.value',
    'tub_6_z': 'tuberias.tuberias[5].cota.value',
    'tub_6_emboquillado': 'tuberias.tuberias[5].emboquillado.value',
    'tub_7_z': 'tuberias.tuberias[6].cota.value',
    'tub_7_emboquillado': 'tuberias.tuberias[6].emboquillado.value',
    'tub_8_z': 'tuberias.tuberias[7].cota.value',
    'tub_8_emboquillado': 'tuberias.tuberias[7].emboquillado.value',

    // SALIDAS (Mapeadas a los índices 8-15 de tuberías)
    'sal_1_id': 'tuberias.tuberias[8].idTuberia.value',
    'sal_1_diametro': 'tuberias.tuberias[8].diametro.value',
    'sal_1_material': 'tuberias.tuberias[8].material.value',
    'sal_1_estado': 'tuberias.tuberias[8].estado.value',
    'sal_1_orden': 'tuberias.tuberias[8].orden.value',
    'sal_1_batea': 'tuberias.tuberias[8].batea.value',
    'sal_1_z': 'tuberias.tuberias[8].cota.value',
    'sal_1_emboquillado': 'tuberias.tuberias[8].emboquillado.value',

    'sal_2_id': 'tuberias.tuberias[9].idTuberia.value',
    'sal_2_diametro': 'tuberias.tuberias[9].diametro.value',
    'sal_2_material': 'tuberias.tuberias[9].material.value',
    'sal_2_estado': 'tuberias.tuberias[9].estado.value',
    'sal_2_orden': 'tuberias.tuberias[9].orden.value',
    'sal_2_batea': 'tuberias.tuberias[9].batea.value',
    'sal_2_z': 'tuberias.tuberias[9].cota.value',
    'sal_2_emboquillado': 'tuberias.tuberias[9].emboquillado.value',

    'sal_3_id': 'tuberias.tuberias[10].idTuberia.value',
    'sal_3_diametro': 'tuberias.tuberias[10].diametro.value',
    'sal_3_material': 'tuberias.tuberias[10].material.value',
    'sal_3_estado': 'tuberias.tuberias[10].estado.value',
    'sal_3_orden': 'tuberias.tuberias[10].orden.value',
    'sal_3_batea': 'tuberias.tuberias[10].batea.value',
    'sal_3_z': 'tuberias.tuberias[10].cota.value',
    'sal_3_emboquillado': 'tuberias.tuberias[10].emboquillado.value',

    // SUMIDEROS (Hasta 4 slots)
    'sum_1_tipo': 'sumideros.sumideros[0].tipoSumidero.value',
    'sum_1_material': 'sumideros.sumideros[0].materialTuberia.value',
    'sum_1_esquema': 'sumideros.sumideros[0].numeroEsquema.value',
    'sum_1_diametro': 'sumideros.sumideros[0].diametro.value',
    'sum_1_hSalida': 'sumideros.sumideros[0].alturaSalida.value',
    'sum_1_hLlegada': 'sumideros.sumideros[0].alturaLlegada.value',
    'sum_2_tipo': 'sumideros.sumideros[1].tipoSumidero.value',
    'sum_2_material': 'sumideros.sumideros[1].materialTuberia.value',
    'sum_2_esquema': 'sumideros.sumideros[1].numeroEsquema.value',
    'sum_2_diametro': 'sumideros.sumideros[1].diametro.value',
    'sum_2_hSalida': 'sumideros.sumideros[1].alturaSalida.value',
    'sum_2_hLlegada': 'sumideros.sumideros[1].alturaLlegada.value',
    'sum_3_tipo': 'sumideros.sumideros[2].tipoSumidero.value',
    'sum_3_material': 'sumideros.sumideros[2].materialTuberia.value',
    'sum_3_esquema': 'sumideros.sumideros[2].numeroEsquema.value',
    'sum_3_diametro': 'sumideros.sumideros[2].diametro.value',
    'sum_3_hSalida': 'sumideros.sumideros[2].alturaSalida.value',
    'sum_3_hLlegada': 'sumideros.sumideros[2].alturaLlegada.value',
    'sum_4_tipo': 'sumideros.sumideros[3].tipoSumidero.value',
    'sum_4_material': 'sumideros.sumideros[3].materialTuberia.value',
    'sum_4_esquema': 'sumideros.sumideros[3].numeroEsquema.value',
    'sum_4_diametro': 'sumideros.sumideros[3].diametro.value',
    'sum_4_hSalida': 'sumideros.sumideros[3].alturaSalida.value',
    'sum_4_hLlegada': 'sumideros.sumideros[3].alturaLlegada.value',
    'sum_5_tipo': 'sumideros.sumideros[4].tipoSumidero.value',
    'sum_5_material': 'sumideros.sumideros[4].materialTuberia.value',
    'sum_5_esquema': 'sumideros.sumideros[4].numeroEsquema.value',
    'sum_5_diametro': 'sumideros.sumideros[4].diametro.value',
    'sum_5_hSalida': 'sumideros.sumideros[4].alturaSalida.value',
    'sum_5_hLlegada': 'sumideros.sumideros[4].alturaLlegada.value',
    'sum_6_tipo': 'sumideros.sumideros[5].tipoSumidero.value',
    'sum_6_material': 'sumideros.sumideros[5].materialTuberia.value',
    'sum_6_esquema': 'sumideros.sumideros[5].numeroEsquema.value',
    'sum_6_diametro': 'sumideros.sumideros[5].diametro.value',
    'sum_6_hSalida': 'sumideros.sumideros[5].alturaSalida.value',
    'sum_6_hLlegada': 'sumideros.sumideros[5].alturaLlegada.value',
    'sum_1_id': 'sumideros.sumideros[0].idSumidero.value',
    'sum_2_id': 'sumideros.sumideros[1].idSumidero.value',
    'sum_3_id': 'sumideros.sumideros[2].idSumidero.value',
    'sum_4_id': 'sumideros.sumideros[3].idSumidero.value',
    'sum_5_id': 'sumideros.sumideros[4].idSumidero.value',
    'sum_6_id': 'sumideros.sumideros[5].idSumidero.value',

    // FOTOS ESPECÍFICAS (Mapeo por subcategoría)
    'foto_panoramica': 'fotos.fotos[P]',
    'foto_tapa': 'fotos.fotos[T]',
    'foto_interior': 'fotos.fotos[I]',
    'foto_acceso': 'fotos.fotos[A]',
    'foto_fondo': 'fotos.fotos[F]',
    'foto_medicion': 'fotos.fotos[M]',
    'foto_esquema': 'fotos.fotos[L]',

    // ENTRADAS (1-7)
    'foto_entrada_1': 'fotos.fotos[E1]',
    'foto_entrada_2': 'fotos.fotos[E2]',
    'foto_entrada_3': 'fotos.fotos[E3]',
    'foto_entrada_4': 'fotos.fotos[E4]',
    'foto_entrada_5': 'fotos.fotos[E5]',
    'foto_entrada_6': 'fotos.fotos[E6]',
    'foto_entrada_7': 'fotos.fotos[E7]',

    // SALIDAS (1-7)
    'foto_salida_1': 'fotos.fotos[S1]',
    'foto_salida_2': 'fotos.fotos[S2]',
    'foto_salida_3': 'fotos.fotos[S3]',
    'foto_salida_4': 'fotos.fotos[S4]',
    'foto_salida_5': 'fotos.fotos[S5]',
    'foto_salida_6': 'fotos.fotos[S6]',
    'foto_salida_7': 'fotos.fotos[S7]',

    // SUMIDEROS (1-7)
    'foto_sumidero_1': 'fotos.fotos[SUM1]',
    'foto_sumidero_2': 'fotos.fotos[SUM2]',
    'foto_sumidero_3': 'fotos.fotos[SUM3]',
    'foto_sumidero_4': 'fotos.fotos[SUM4]',
    'foto_sumidero_5': 'fotos.fotos[SUM5]',
    'foto_sumidero_6': 'fotos.fotos[SUM6]',
    'foto_sumidero_7': 'fotos.fotos[SUM7]',

    // DESCARGAS (1-7)
    'foto_descarga_1': 'fotos.fotos[D1]',
    'foto_descarga_2': 'fotos.fotos[D2]',
    'foto_descarga_3': 'fotos.fotos[D3]',
    'foto_descarga_4': 'fotos.fotos[D4]',
    'foto_descarga_5': 'fotos.fotos[D5]',
    'foto_descarga_6': 'fotos.fotos[D6]',
    'foto_descarga_7': 'fotos.fotos[D7]',

    // FOTOS GENÉRICAS (Fallback para fotos no clasificadas)
    'foto_1': 'fotos.fotos[0].blobId',
    'foto_2': 'fotos.fotos[1].blobId',
    'foto_3': 'fotos.fotos[2].blobId',
    'foto_4': 'fotos.fotos[3].blobId',
    'foto_5': 'fotos.fotos[4].blobId',
    'foto_6': 'fotos.fotos[5].blobId',
    'foto_7': 'fotos.fotos[6].blobId',
    'foto_8': 'fotos.fotos[7].blobId',
    'foto_9': 'fotos.fotos[8].blobId',
    'foto_10': 'fotos.fotos[9].blobId',
    'foto_11': 'fotos.fotos[10].blobId',
    'foto_12': 'fotos.fotos[11].blobId',

    // Alias heredados del legacy para compatibilidad
    'identificacion.idPozo': 'identificacion.idPozo.value',
    'identificacion.fecha': 'identificacion.fecha.value',
    'identificacion.coordenadaX': 'identificacion.coordenadaX.value',
    'identificacion.coordenadaY': 'identificacion.coordenadaY.value',
};

export const AVAILABLE_DATA_FIELDS = [
    { id: 'pozo_id', label: 'ID del Pozo', category: 'Identificación' },
    { id: 'pozo_fecha', label: 'Fecha', category: 'Identificación' },
    { id: 'pozo_levanto', label: 'Levantó', category: 'Identificación' },
    { id: 'pozo_estado', label: 'Estado', category: 'Identificación' },
    { id: 'pozo_coordX', label: 'Coordenada X', category: 'Ubicación' },
    { id: 'pozo_coordY', label: 'Coordenada Y', category: 'Ubicación' },
    { id: 'pozo_latitud', label: 'Latitud (WGS84)', category: 'Ubicación' },
    { id: 'pozo_longitud', label: 'Longitud (WGS84)', category: 'Ubicación' },
    { id: 'pozo_enlace', label: 'Enlace Google Maps', category: 'Ubicación' },
    { id: 'pozo_direccion', label: 'Dirección', category: 'Ubicación' },
    { id: 'pozo_barrio', label: 'Barrio', category: 'Ubicación' },
    { id: 'pozo_localidad', label: 'Localidad', category: 'Ubicación' },
    { id: 'pozo_upz', label: 'UPZ', category: 'Ubicación' },
    { id: 'pozo_profundidad', label: 'Profundidad', category: 'Ubicación' },
    { id: 'pozo_materialTapa', label: 'Mat. Tapa', category: 'Componentes' },
    { id: 'pozo_estadoTapa', label: 'Estado Tapa', category: 'Componentes' },
    { id: 'pozo_diametroCilindro', label: 'Ø Cilindro', category: 'Componentes' },
    { id: 'pozo_materialCono', label: 'Mat. Cono', category: 'Componentes' },
    { id: 'pozo_materialCanuela', label: 'Mat. Cañuela', category: 'Componentes' },
    { id: 'pozo_numPeldanos', label: 'Nº Peldaños', category: 'Componentes' },
    { id: 'pozo_observaciones', label: 'Observaciones', category: 'Observaciones' },
    // Tuberías Completas (8 slots)
    { id: 'tub_1_id', label: 'Tub 1 ID', category: 'Tuberías' },
    { id: 'tub_1_estado', label: 'Tub 1 Est', category: 'Tuberías' },
    { id: 'tub_1_diametro', label: 'Tub 1 Ø', category: 'Tuberías' },
    { id: 'tub_1_material', label: 'Tub 1 Material', category: 'Tuberías' },
    { id: 'tub_1_orden', label: 'Tub 1 Orden', category: 'Tuberías' },
    { id: 'tub_1_batea', label: 'Tub 1 Batea', category: 'Tuberías' },
    { id: 'tub_1_z', label: 'Tub 1 Prof. clave (m)', category: 'Tuberías' },
    { id: 'tub_1_emboquillado', label: 'Tub 1 Emb.', category: 'Tuberías' },

    { id: 'tub_2_id', label: 'Tub 2 ID', category: 'Tuberías' },
    { id: 'tub_2_estado', label: 'Tub 2 Est', category: 'Tuberías' },
    { id: 'tub_2_diametro', label: 'Tub 2 Ø', category: 'Tuberías' },
    { id: 'tub_2_material', label: 'Tub 2 Material', category: 'Tuberías' },
    { id: 'tub_2_orden', label: 'Tub 2 Orden', category: 'Tuberías' },
    { id: 'tub_2_batea', label: 'Tub 2 Batea', category: 'Tuberías' },
    { id: 'tub_2_z', label: 'Tub 2 Prof. clave (m)', category: 'Tuberías' },
    { id: 'tub_2_emboquillado', label: 'Tub 2 Emb.', category: 'Tuberías' },

    { id: 'tub_3_id', label: 'Tub 3 ID', category: 'Tuberías' },
    { id: 'tub_3_estado', label: 'Tub 3 Est', category: 'Tuberías' },
    { id: 'tub_3_diametro', label: 'Tub 3 Ø', category: 'Tuberías' },
    { id: 'tub_3_material', label: 'Tub 3 Material', category: 'Tuberías' },
    { id: 'tub_3_orden', label: 'Tub 3 Orden', category: 'Tuberías' },
    { id: 'tub_3_batea', label: 'Tub 3 Batea', category: 'Tuberías' },
    { id: 'tub_3_z', label: 'Tub 3 Prof. clave (m)', category: 'Tuberías' },
    { id: 'tub_3_emboquillado', label: 'Tub 3 Emb.', category: 'Tuberías' },

    { id: 'tub_4_id', label: 'Tub 4 ID', category: 'Tuberías' },
    { id: 'tub_4_estado', label: 'Tub 4 Est', category: 'Tuberías' },
    { id: 'tub_4_diametro', label: 'Tub 4 Ø', category: 'Tuberías' },
    { id: 'tub_4_material', label: 'Tub 4 Material', category: 'Tuberías' },
    { id: 'tub_4_orden', label: 'Tub 4 Orden', category: 'Tuberías' },
    { id: 'tub_4_batea', label: 'Tub 4 Batea', category: 'Tuberías' },
    { id: 'tub_4_z', label: 'Tub 4 Prof. clave (m)', category: 'Tuberías' },
    { id: 'tub_4_emboquillado', label: 'Tub 4 Emb.', category: 'Tuberías' },

    { id: 'tub_5_id', label: 'Tub 5 ID', category: 'Tuberías' },
    { id: 'tub_5_estado', label: 'Tub 5 Est', category: 'Tuberías' },
    { id: 'tub_5_diametro', label: 'Tub 5 Ø', category: 'Tuberías' },
    { id: 'tub_5_material', label: 'Tub 5 Material', category: 'Tuberías' },
    { id: 'tub_5_orden', label: 'Tub 5 Orden', category: 'Tuberías' },
    { id: 'tub_5_batea', label: 'Tub 5 Batea', category: 'Tuberías' },
    { id: 'tub_5_z', label: 'Tub 5 Prof. clave (m)', category: 'Tuberías' },
    { id: 'tub_5_emboquillado', label: 'Tub 5 Emb.', category: 'Tuberías' },

    { id: 'tub_6_id', label: 'Tub 6 ID', category: 'Tuberías' },
    { id: 'tub_6_estado', label: 'Tub 6 Est', category: 'Tuberías' },
    { id: 'tub_6_diametro', label: 'Tub 6 Ø', category: 'Tuberías' },
    { id: 'tub_6_material', label: 'Tub 6 Material', category: 'Tuberías' },
    { id: 'tub_6_orden', label: 'Tub 6 Orden', category: 'Tuberías' },
    { id: 'tub_6_batea', label: 'Tub 6 Batea', category: 'Tuberías' },
    { id: 'tub_6_z', label: 'Tub 6 Prof. clave (m)', category: 'Tuberías' },
    { id: 'tub_6_emboquillado', label: 'Tub 6 Emb.', category: 'Tuberías' },

    { id: 'tub_7_id', label: 'Tub 7 ID', category: 'Tuberías' },
    { id: 'tub_7_estado', label: 'Tub 7 Est', category: 'Tuberías' },
    { id: 'tub_7_diametro', label: 'Tub 7 Ø', category: 'Tuberías' },
    { id: 'tub_7_material', label: 'Tub 7 Material', category: 'Tuberías' },
    { id: 'tub_7_orden', label: 'Tub 7 Orden', category: 'Tuberías' },
    { id: 'tub_7_batea', label: 'Tub 7 Batea', category: 'Tuberías' },
    { id: 'tub_7_z', label: 'Tub 7 Prof. clave (m)', category: 'Tuberías' },
    { id: 'tub_7_emboquillado', label: 'Tub 7 Emb.', category: 'Tuberías' },

    { id: 'tub_8_id', label: 'Tub 8 ID', category: 'Tuberías' },
    { id: 'tub_8_estado', label: 'Tub 8 Est', category: 'Tuberías' },
    { id: 'tub_8_diametro', label: 'Tub 8 Ø', category: 'Tuberías' },
    { id: 'tub_8_material', label: 'Tub 8 Material', category: 'Tuberías' },
    { id: 'tub_8_orden', label: 'Tub 8 Orden', category: 'Tuberías' },
    { id: 'tub_8_batea', label: 'Tub 8 Batea', category: 'Tuberías' },
    { id: 'tub_8_z', label: 'Tub 8 Prof. clave (m)', category: 'Tuberías' },
    { id: 'tub_8_emboquillado', label: 'Tub 8 Emb.', category: 'Tuberías' },

    // Salidas (Slots 1-3 para empezar)
    { id: 'sal_1_id', label: 'Salida 1 ID', category: 'Salidas' },
    { id: 'sal_1_diametro', label: 'Salida 1 Ø', category: 'Salidas' },
    { id: 'sal_1_material', label: 'Salida 1 Material', category: 'Salidas' },
    { id: 'sal_1_orden', label: 'Salida 1 Orden', category: 'Salidas' },
    { id: 'sal_1_batea', label: 'Salida 1 Batea', category: 'Salidas' },
    { id: 'sal_1_z', label: 'Salida 1 Prof. clave (m)', category: 'Salidas' },

    { id: 'sal_2_id', label: 'Salida 2 ID', category: 'Salidas' },
    { id: 'sal_2_diametro', label: 'Salida 2 Ø', category: 'Salidas' },
    { id: 'sal_2_material', label: 'Salida 2 Material', category: 'Salidas' },
    { id: 'sal_2_z', label: 'Salida 2 Prof. clave (m)', category: 'Salidas' },
    { id: 'sum_1_tipo', label: 'Sum 1 Tipo', category: 'Sumideros' },
    { id: 'sum_1_material', label: 'Sum 1 Mat', category: 'Sumideros' },
    { id: 'sum_1_esquema', label: 'Sum 1 Esquema', category: 'Sumideros' },
    { id: 'sum_1_diametro', label: 'Sum 1 Ø (pulg)', category: 'Sumideros' },
    { id: 'sum_1_hSalida', label: 'Sum 1 H Salida', category: 'Sumideros' },
    { id: 'sum_1_hLlegada', label: 'Sum 1 H Llegada', category: 'Sumideros' },

    { id: 'sum_2_tipo', label: 'Sum 2 Tipo', category: 'Sumideros' },
    { id: 'sum_2_material', label: 'Sum 2 Mat', category: 'Sumideros' },
    { id: 'sum_2_esquema', label: 'Sum 2 Esquema', category: 'Sumideros' },
    { id: 'sum_2_diametro', label: 'Sum 2 Ø (pulg)', category: 'Sumideros' },
    { id: 'sum_2_hSalida', label: 'Sum 2 H Salida', category: 'Sumideros' },
    { id: 'sum_2_hLlegada', label: 'Sum 2 H Llegada', category: 'Sumideros' },

    { id: 'sum_3_tipo', label: 'Sum 3 Tipo', category: 'Sumideros' },
    { id: 'sum_3_material', label: 'Sum 3 Mat', category: 'Sumideros' },
    { id: 'sum_3_esquema', label: 'Sum 3 Esquema', category: 'Sumideros' },
    { id: 'sum_3_diametro', label: 'Sum 3 Ø (pulg)', category: 'Sumideros' },
    { id: 'sum_3_hSalida', label: 'Sum 3 H Salida', category: 'Sumideros' },
    { id: 'sum_3_hLlegada', label: 'Sum 3 H Llegada', category: 'Sumideros' },

    { id: 'sum_4_tipo', label: 'Sum 4 Tipo', category: 'Sumideros' },
    { id: 'sum_4_material', label: 'Sum 4 Mat', category: 'Sumideros' },
    { id: 'sum_4_esquema', label: 'Sum 4 Esquema', category: 'Sumideros' },
    { id: 'sum_4_diametro', label: 'Sum 4 Ø (pulg)', category: 'Sumideros' },
    { id: 'sum_4_hSalida', label: 'Sum 4 H Salida', category: 'Sumideros' },
    { id: 'sum_4_hLlegada', label: 'Sum 4 H Llegada', category: 'Sumideros' },

    { id: 'sum_5_tipo', label: 'Sum 5 Tipo', category: 'Sumideros' },
    { id: 'sum_5_material', label: 'Sum 5 Mat', category: 'Sumideros' },
    { id: 'sum_5_esquema', label: 'Sum 5 Esquema', category: 'Sumideros' },
    { id: 'sum_5_diametro', label: 'Sum 5 Ø (pulg)', category: 'Sumideros' },
    { id: 'sum_5_hSalida', label: 'Sum 5 H Salida', category: 'Sumideros' },
    { id: 'sum_5_hLlegada', label: 'Sum 5 H Llegada', category: 'Sumideros' },

    { id: 'sum_6_tipo', label: 'Sum 6 Tipo', category: 'Sumideros' },
    { id: 'sum_6_material', label: 'Sum 6 Mat', category: 'Sumideros' },
    { id: 'sum_6_esquema', label: 'Sum 6 Esquema', category: 'Sumideros' },
    { id: 'sum_6_diametro', label: 'Sum 6 Ø (pulg)', category: 'Sumideros' },
    { id: 'sum_6_hSalida', label: 'Sum 6 H Salida', category: 'Sumideros' },
    { id: 'sum_6_hLlegada', label: 'Sum 6 H Llegada', category: 'Sumideros' },
    { id: 'sum_1_id', label: 'Sum 1 ID', category: 'Sumideros' },
    { id: 'sum_2_id', label: 'Sum 2 ID', category: 'Sumideros' },
    { id: 'sum_3_id', label: 'Sum 3 ID', category: 'Sumideros' },
    { id: 'sum_4_id', label: 'Sum 4 ID', category: 'Sumideros' },
    { id: 'sum_5_id', label: 'Sum 5 ID', category: 'Sumideros' },
    { id: 'sum_6_id', label: 'Sum 6 ID', category: 'Sumideros' },
    { id: 'foto_panoramica', label: 'Foto Panorámica (P)', category: 'Fotos' },
    { id: 'foto_tapa', label: 'Foto Tapa (T)', category: 'Fotos' },
    { id: 'foto_interior', label: 'Foto Interna (I)', category: 'Fotos' },
    { id: 'foto_acceso', label: 'Foto Acceso (A)', category: 'Fotos' },
    { id: 'foto_fondo', label: 'Foto Fondo (F)', category: 'Fotos' },
    { id: 'foto_medicion', label: 'Foto Medición (M)', category: 'Fotos' },
    { id: 'foto_esquema', label: 'Esquema Localización (L)', category: 'Fotos' },

    // Fotos Entradas
    { id: 'foto_entrada_1', label: 'Foto Entrada 1', category: 'Fotos Tuberías' },
    { id: 'foto_entrada_2', label: 'Foto Entrada 2', category: 'Fotos Tuberías' },
    { id: 'foto_entrada_3', label: 'Foto Entrada 3', category: 'Fotos Tuberías' },
    { id: 'foto_entrada_4', label: 'Foto Entrada 4', category: 'Fotos Tuberías' },
    { id: 'foto_entrada_5', label: 'Foto Entrada 5', category: 'Fotos Tuberías' },
    { id: 'foto_entrada_6', label: 'Foto Entrada 6', category: 'Fotos Tuberías' },
    { id: 'foto_entrada_7', label: 'Foto Entrada 7', category: 'Fotos Tuberías' },

    // Fotos Salidas
    { id: 'foto_salida_1', label: 'Foto Salida 1', category: 'Fotos Tuberías' },
    { id: 'foto_salida_2', label: 'Foto Salida 2', category: 'Fotos Tuberías' },
    { id: 'foto_salida_3', label: 'Foto Salida 3', category: 'Fotos Tuberías' },
    { id: 'foto_salida_4', label: 'Foto Salida 4', category: 'Fotos Tuberías' },
    { id: 'foto_salida_5', label: 'Foto Salida 5', category: 'Fotos Tuberías' },
    { id: 'foto_salida_6', label: 'Foto Salida 6', category: 'Fotos Tuberías' },
    { id: 'foto_salida_7', label: 'Foto Salida 7', category: 'Fotos Tuberías' },

    // Fotos Sumideros
    { id: 'foto_sumidero_1', label: 'Foto Sumidero 1', category: 'Fotos Sumideros' },
    { id: 'foto_sumidero_2', label: 'Foto Sumidero 2', category: 'Fotos Sumideros' },
    { id: 'foto_sumidero_3', label: 'Foto Sumidero 3', category: 'Fotos Sumideros' },
    { id: 'foto_sumidero_4', label: 'Foto Sumidero 4', category: 'Fotos Sumideros' },
    { id: 'foto_sumidero_5', label: 'Foto Sumidero 5', category: 'Fotos Sumideros' },
    { id: 'foto_sumidero_6', label: 'Foto Sumidero 6', category: 'Fotos Sumideros' },
    { id: 'foto_sumidero_7', label: 'Foto Sumidero 7', category: 'Fotos Sumideros' },

    // Fotos Descargas
    { id: 'foto_descarga_1', label: 'Foto Descarga 1', category: 'Fotos Envío' },
    { id: 'foto_descarga_2', label: 'Foto Descarga 2', category: 'Fotos Envío' },
    { id: 'foto_descarga_3', label: 'Foto Descarga 3', category: 'Fotos Envío' },
    { id: 'foto_descarga_4', label: 'Foto Descarga 4', category: 'Fotos Envío' },
    { id: 'foto_descarga_5', label: 'Foto Descarga 5', category: 'Fotos Envío' },
    { id: 'foto_descarga_6', label: 'Foto Descarga 6', category: 'Fotos Envío' },
    { id: 'foto_descarga_7', label: 'Foto Descarga 7', category: 'Fotos Envío' },
];
